fix: mac adaption

diff --git a/.chezmoiscripts/run_onchange_after_install_packages.sh.tmpl b/.chezmoiscripts/run_onchange_after_install_packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange_after_install_packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_after_install_packages.sh.tmpl
@@ -1,3 +1,11 @@
 #!/bin/bash
 # packages hash: {{ include "dot_config/mise/config.toml" | sha256sum }}
-$HOME/.local/bin/mise trust $HOME/.config/mise/config.toml && $HOME/.local/bin/mise install
+
+MISE_BIN="$(command -v mise)"
+
+if [[ -z "$MISE_BIN" ]]; then
+  echo "mise not found in path"
+  exit 1
+fi
+
+"$MISE_BIN" trust $HOME/.config/mise/config.toml && "$MISE_BIN" install
